-- #######################################################################################
-- CONFIGURAZIONE HYPRLAND IN LUA (richiede Hyprland >= 0.55)
-- Convertita da hyprland.conf al nuovo formato hyprland.lua
-- Salva questo file come ~/.config/hypr/hyprland.lua
-- Riferimento: https://wiki.hypr.land/Configuring/Start/
--
-- NOTA: i dispatcher usati qui sotto sono stati verificati direttamente contro
-- il sorgente C++ di Hyprland (src/config/lua/bindings/LuaBindingsDispatchers.cpp
-- su github.com/hyprwm/Hyprland), non solo contro wiki/blog di terze parti, dato
-- che l'API è uscita da pochissime settimane (0.55, maggio 2026) e le fonti
-- secondarie contenevano ancora inesattezze. Fai comunque `hyprctl reload` con
-- un terminale aperto dopo il salvataggio, per vedere subito eventuali errori.
-- #######################################################################################

-- Rimuovi/commenta questa riga per togliere il banner giallo "autogenerated"
-- hl.config({ autogenerated = true })

-- Puoi (e dovresti!) dividere la configurazione in più file con require("nomefile")


------------------
---- MONITORS ----
------------------

-- https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})


------------------------
---- MIEI PROGRAMMI ----
------------------------

local terminal    = "kitty"
local fileManager = "nautilus --new-window"
local menu        = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

-- https://wiki.hypr.land/Configuring/Basics/Autostart/
-- exec-once diventa: eseguire i comandi dentro l'evento "hyprland.start"
hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("bluetoothctl power off")
    hl.exec_cmd("nwg-dock-hyprland -d")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Le modifiche ai permessi richiedono un riavvio di Hyprland e non si
-- applicano "a caldo", per motivi di sicurezza

-- hl.config({
--     ecosystem = {
--         enforce_permissions = true,
--     },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,

        border_size = 0,
        col = {
            active_border   = "rgba(F5F5F5aa)",
            inactive_border = "rgba(F5F5F5aa)",
        },

        -- true per ridimensionare le finestre trascinando bordi e gap
        resize_on_border = false,

        -- vedi https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ prima di attivarlo
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = 0,
        rounding_power = 2,

        -- Trasparenza finestra attiva/inattiva
        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = false,
            range = 10,
            render_power = 4,
            color = "rgba(1a1a1aee)",
        },

        -- https://wiki.hypr.land/Configuring/Basics/Variables/#blur
        blur = {
            enabled = true,
            size = 8,
            passes = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Curve di default, vedi https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInQuint",    { type = "bezier", points = { {0.83, 0},    {0.17, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},      {1, 1} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},  {0.75, 1} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},   {0.1, 1} } })
hl.curve("solida",         { type = "bezier", points = { {1, 0},      {1, 0} } })

-- Animazioni di default
hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "slide bottom" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 4.1,  bezier = "almostLinear", style = "slide bottom" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 2.0,  bezier = "solida" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })


-- Layer rules: https://wiki.hypr.land/Configuring/Basics/Layer-Rules/
hl.layer_rule({
    name = "animazione_waybar",
    match = { namespace = "waybar" },
    animation = "slide top", -- TODO: verifica il nome del campo "animation" sulla wiki
})

hl.layer_rule({
    name = "animazione_dock",
    match = { namespace = "nwg-dock-hyprland" },
    animation = "slide left", -- TODO: come sopra
})

hl.layer_rule({
    match = { namespace = "rofi" },
    blur = true,
    ignore_alpha = 0.2,
})


-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "Niente gap se c'è una sola finestra"
-- decommenta tutto se vuoi usarlo
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding = 0,
-- })
-- hl.window_rule({
--     name = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding = 0,
-- })

-- https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/
hl.config({
    dwindle = {
        preserve_split = true, -- probabilmente lo vuoi
    },
})

-- https://wiki.hypr.land/Configuring/Layouts/Master-Layout/
hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Basics/Variables/#misc
hl.config({
    misc = {
        force_default_wallpaper = -1, -- 0 o 1 per disabilitare gli sfondi anime
        disable_hyprland_logo = false, -- true disabilita il logo/anime girl casuale. :(
    },
})


-------------
---- INPUT ----
-------------

hl.config({
    input = {
        kb_layout  = "it",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 2,

        sensitivity = 0.5, -- -1.0 - 1.0, 0 = nessuna modifica

        touchpad = {
            natural_scroll = true,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Esempio di configurazione per dispositivo specifico
-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

-- https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- Imposta il tasto "Windows" come modificatore principale

hl.bind("CTRL + T", hl.dsp.exec_cmd(terminal))
hl.bind("ALT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd(menu), { release = true })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- dwindle

-- Sposta la finestra all'interno dello stesso workspace
-- (verificato contro il sorgente C++ di Hyprland: hl.dsp.window.move({direction=...}) è corretto)
hl.bind("CTRL + left",  hl.dsp.window.move({ direction = "l" }))
hl.bind("CTRL + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("CTRL + up",    hl.dsp.window.move({ direction = "u" }))
hl.bind("CTRL + down",  hl.dsp.window.move({ direction = "d" }))

-- Sposta il focus con ALT + TAB
-- Il dispatcher si chiama "cycle_next" (non "cycle") e usa un campo booleano
-- "next" (non "direction"). Verificato leggendo direttamente il sorgente C++
-- (src/config/lua/bindings/LuaBindingsDispatchers.cpp, funzione hlWindowCycleNext).
hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("ALT + SHIFT + Tab", hl.dsp.window.cycle_next({ next = false }))

-- Ridimensiona finestra
-- "relative = true" è necessario: senza, x/y vengono trattati come dimensione
-- assoluta e non come incremento, e la finestra verrebbe ridimensionata a 30x0px.
hl.bind("ALT + right", hl.dsp.window.resize({ x = 30,  y = 0,   relative = true }), { repeating = true })
hl.bind("ALT + left",  hl.dsp.window.resize({ x = -30, y = 0,   relative = true }), { repeating = true })
hl.bind("ALT + up",    hl.dsp.window.resize({ x = 0,   y = -30, relative = true }), { repeating = true })
hl.bind("ALT + down",  hl.dsp.window.resize({ x = 0,   y = 30,  relative = true }), { repeating = true })

-- Killa e riavvia waybar
hl.bind("XF86Favorites", hl.dsp.exec_cmd("pkill -x waybar || waybar"))

-- Avvia hyprlock
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("systemctl suspend && hyprlock"))

-- Cattura screenshot
hl.bind("XF86SelectiveScreenshot", hl.dsp.exec_cmd('hyprshot -m region -o "/home/vito/Pictures/Screenshots/"'))

-- attivare walt per impostare force_defaultwallpaper
hl.bind("ALT + W", hl.dsp.exec_cmd("kitty walt"))

-- Sposta la finestra attiva su un workspace con mainMod + [0-9]
-- (nel file originale il commento parlava di mainMod+SHIFT, ma i bind usavano
-- solo mainMod: tradotto 1:1 così com'era, comportamento invariato)
for i = 1, 10 do
    local key = i % 10 -- il tasto "0" corrisponde al workspace 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Esempio di workspace speciale (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scorri tra i workspace esistenti con mainMod + rotellina
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Sposta/ridimensiona le finestre con mainMod + click sinistro/destro e trascinamento
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Tasti multimediali del laptop per volume e luminosità LCD
-- Volume (mantenendo il tuo limite di -l 1 per non superare il 100%)
hl.bind("XF86AudioRaiseVolume",
    hl.dsp.exec_cmd([[bash -c "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}' | xargs -I {} notify-send -a 'Audio' -h string:x-dunst-stack-tag:volume -h int:value:{} 'Volume: {}%'"]]),
    { repeating = true, locked = true })

hl.bind("XF86AudioLowerVolume",
    hl.dsp.exec_cmd([[bash -c "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}' | xargs -I {} notify-send -a 'Audio' -h string:x-dunst-stack-tag:volume -h int:value:{} 'Volume: {}%'"]]),
    { repeating = true, locked = true })

-- Muto (Cuffie/Speaker)
hl.bind("XF86AudioMute",
    hl.dsp.exec_cmd([[bash -c "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send -a 'Audio' -h string:x-dunst-stack-tag:volume 'Audio Muto / Riattivato'"]]),
    { repeating = true, locked = true })

-- Muto (Microfono)
hl.bind("XF86AudioMicMute",
    hl.dsp.exec_cmd([[bash -c "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && notify-send -a 'Microfono' -h string:x-dunst-stack-tag:mic 'Microfono Muto / Riattivato'"]]),
    { repeating = true, locked = true })

-- Luminosità (mantenendo i tuoi flag speciali -e4 -n2)
hl.bind("XF86MonBrightnessUp",
    hl.dsp.exec_cmd([[bash -c "brightnessctl -e4 -n2 set 5%+ && brightnessctl i | awk '/Current/ {print $4}' | tr -d '()%' | xargs -I {} notify-send -a 'Display' -h string:x-dunst-stack-tag:brightness -h int:value:{} 'Luminosità: {}%'"]]),
    { repeating = true, locked = true })

hl.bind("XF86MonBrightnessDown",
    hl.dsp.exec_cmd([[bash -c "brightnessctl -e4 -n2 set 5%- && brightnessctl i | awk '/Current/ {print $4}' | tr -d '()%' | xargs -I {} notify-send -a 'Display' -h string:x-dunst-stack-tag:brightness -h int:value:{} 'Luminosità: {}%'"]]),
    { repeating = true, locked = true })

-- Richiede playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Bluetooth e wifi
hl.bind("SHIFT + Control_L", hl.dsp.exec_cmd("kitty bluetui"))
hl.bind("ALT + Control_L",   hl.dsp.exec_cmd("kitty impala"))


--------------------------------
---- FINESTRE E WORKSPACE ----
--------------------------------

-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

hl.window_rule({
    -- Ignora le richieste di massimizzazione da tutte le app. Probabilmente ti piacerà.
    name = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    -- Corregge alcuni problemi di trascinamento con XWayland
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})


-------------
---- DEBUG ----
-------------

hl.config({
    debug = {
        vfr = true, -- Abilita il Variable Frame Rate per risparmiare batteria
    },
})
